// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGdOUan-n-HgPF5LiWM6DZkmV2GOmv7ts',
    appId: '1:935168308538:web:86afb679a05173a3930c03',
    messagingSenderId: '935168308538',
    projectId: 'monchi-ai-companion-app-43b1a',
    authDomain: 'monchi-ai-companion-app-43b1a.firebaseapp.com',
    storageBucket: 'monchi-ai-companion-app-43b1a.firebasestorage.app',
    measurementId: 'G-PRRND3TSJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq5Z6C0tJzXiuxA8Yo5LG8PjSUkobJtkY',
    appId: '1:935168308538:android:9b4d6da01bd2af56930c03',
    messagingSenderId: '935168308538',
    projectId: 'monchi-ai-companion-app-43b1a',
    storageBucket: 'monchi-ai-companion-app-43b1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvBmGirbQXmBG5WociFdwtrPHb4A-0DOc',
    appId: '1:935168308538:ios:a40ec62c355a77ed930c03',
    messagingSenderId: '935168308538',
    projectId: 'monchi-ai-companion-app-43b1a',
    storageBucket: 'monchi-ai-companion-app-43b1a.firebasestorage.app',
    iosBundleId: 'com.example.monchi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvBmGirbQXmBG5WociFdwtrPHb4A-0DOc',
    appId: '1:935168308538:ios:a40ec62c355a77ed930c03',
    messagingSenderId: '935168308538',
    projectId: 'monchi-ai-companion-app-43b1a',
    storageBucket: 'monchi-ai-companion-app-43b1a.firebasestorage.app',
    iosBundleId: 'com.example.monchi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGdOUan-n-HgPF5LiWM6DZkmV2GOmv7ts',
    appId: '1:935168308538:web:ad2ebe1b92ce987c930c03',
    messagingSenderId: '935168308538',
    projectId: 'monchi-ai-companion-app-43b1a',
    authDomain: 'monchi-ai-companion-app-43b1a.firebaseapp.com',
    storageBucket: 'monchi-ai-companion-app-43b1a.firebasestorage.app',
    measurementId: 'G-S4M9TZV15V',
  );
}
